Controllers/CourseController.cs
using Hafiz136.Database;
using Hafiz136.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hafiz136.Controllers
{
    public class CourseController : Controller
    {
        private readonly DataBaseconnection _context;

        public CourseController(DataBaseconnection data)
        {
            _context = data;
        }
        
        public ActionResult Index()
        {
            var k = _context.courses.ToList();
            return View(k);
        }

       
        public ActionResult Details(int? id)
        {
            var k = _context.courses.FirstOrDefault(k => k.Id == id);
            return View(k);
        }

       
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
      
        public ActionResult Create(Course course)
        {
            _context.courses.Add(course);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


       
        public ActionResult Edit(int? id)
        {
            var k = _context.courses.Find(id);
            return View(k);
        }

       
        [HttpPost]
        
        public ActionResult Edit(int id, Course course)
        {
            _context.Update(course);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

      
        public ActionResult Delete(int? id)
        {
            var k = _context.courses.FirstOrDefault(k => k.Id == id);
            return View(k);
           
        }

      
        [HttpPost]
       
        public ActionResult Delete(int id, Course course)
        {
            _context.Remove(course);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/StudentController.cs
using Hafiz136.Database;
using Hafiz136.Models;
using Hafiz136.ViewMOdel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Hafiz136.Controllers
{
    public class StudentController : Controller
    {
        private readonly DataBaseconnection _context;
        private readonly IWebHostEnvironment _webHost;

        public StudentController(DataBaseconnection baseconnection, IWebHostEnvironment webHost)
        {
            _context = baseconnection;
            _webHost = webHost;
        }
        public ActionResult Index()
        {
            var k = _context.students.ToList();
            return View(k);
        }

        
        public ActionResult Details(int? id)
        {
            var k = _context.students.FirstOrDefault(k => k.Id == id);
            return View(k);
        }

       
        public ActionResult Create()
        {
            return View();
        }       
        [HttpPost]      
        public ActionResult Create(int id,UploadStudentImage model )
        {
            string uploadfile = uploadimg(model);
            var student = new Student
            {
                Stu_Name=model.Stu_Name,
                Stu_Cell=model.Stu_Cell,
                Student_Picture=uploadfile,
                Email=model.Email
            };
            _context.students.Add(student);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
        //for upload image
        private string uploadimg(UploadStudentImage model)
        {
            string uploadfile = null;
            if (model.Student_Picture!=null)
            {
                var upload = Path.Combine(_webHost.WebRootPath, "Projectimg");
                uploadfile = Guid.NewGuid().ToString()
                + "-" + model.Student_Picture.FileName;
                string fileroote = Path.Combine(upload, uploadfile);
                using (var filestream = new FileStream(fileroote, FileMode.Create))
                {
                    model.Student_Picture.CopyToAsync(filestream);
                }
               
            }

            return uploadfile;
        }
        public ActionResult Edit(int id)
        {
            var k = _context.students.Find(id);
            return View(k);
        }

        [HttpPost]
     
        public ActionResult Edit(int id, Student student)
        {
            _context.Update(student);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

       
        public ActionResult Delete(int id)
        {
            var k = _context.students.FirstOrDefault(k => k.Id == id);
            return View(k);
        }

       
        [HttpPost]
       
        public ActionResult Delete(int id, Student student)
        {
            _context.Remove(student);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Controllers/TeacherController.cs
using Hafiz136.Database;
using Hafiz136.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hafiz136.Controllers
{
    public class TeacherController : Controller
    {
        private DataBaseconnection _data;

        public TeacherController(DataBaseconnection data)
        {
            _data = data;
        }
        public ActionResult Index()
        {
            var k = _data.teachers.ToList();
            return View(k);
        }

        
        public ActionResult Details(int? id)
        {
            var k = _data.teachers.FirstOrDefault(k => k.Id == id);
            return View(k);
        }

       
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
       
        public ActionResult Create(Teacher teacher)
        {
            _data.teachers.Add(teacher);
            _data.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        
        public ActionResult Edit(int id)
        {
            var k = _data.teachers.Find(id);
            return View(k);
        }

       
        [HttpPost]
       
        public ActionResult Edit(int id, Teacher teacher)
        {
            _data.Update(teacher);
            _data.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

       
        public ActionResult Delete(int? id)
        {
            var k = _data.teachers.FirstOrDefault(k => k.Id == id);
            return View(k);
        }

       
        [HttpPost]
      
        public ActionResult Delete(int id, Teacher teacher)
        {
            _data.Remove(teacher);
            _data.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] School Management System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">School Management System</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;2022 University of the sialkot <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>